---
title: "flat_minimal.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Get info data

```{r function-get_info_data}
#' Get info data
#' Function which will allow to have information on a data set passed in parameter: dimensions and name of columns in a list 
#' @return list
#' @export
#'
#' @examples
#' 
get_info_data <- function(data) {
  
  dimensions = dim(data)
  column_names = colnames(data)
  
  result <- list(dimensions = dimensions, column_names = column_names)
  
  if(is.null(result$dimensions) & is.null(result$column_names)){
    stop("This is not a list")
  } else {
    return(result)
  }
    
}
```

```{r examples-get_info_data}
get_info_data(data = iris)
```

```{r tests-get_info_data}
test_that("get_info_data works", {
  expected_output <- list(dimensions=c(150,5),column_names=c("Sepal.Length","Sepal.Width","Petal.Length","Petal.Width","Species"))
  object <- get_info_data(data = iris)
  expect_equal(object, expected_output)
})

test_that("get_info_data do not work", {
  object2 <- "text"
  expect_error(get_info_data(object2), "This is not a list")
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_minimal.Rmd", vignette_name = "Minimal")
```
