# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

test_that("get_mean_data works", {
  expected_output <- iris %>% summarise_if(is.numeric, mean, na.rm = TRUE)
  object <- get_mean_data(iris)
  expect_equal(object, expected_output) 
})

test_that("get_mean_data does not work", {
  object <- iris$Species
  expect_error(get_mean_data(object), "Your data has no numeric variables")
  })
