# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

test_that("get_info_data works", {
  expected_output <- list(dimensions=c(150,5),column_names=c("Sepal.Length","Sepal.Width","Petal.Length","Petal.Width","Species"))
  object <- get_info_data(data = iris)
  expect_equal(object, expected_output)
})

test_that("get_info_data do not work", {
  object2 <- "text"
  expect_error(get_info_data(object2), "This is not a list")
})
