# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' Get info data
#' Function which will allow to have information on a data set passed in parameter: dimensions and name of columns in a list 

#' @return list
#' @export
#'
#' @examples
#' 
#' get_info_data(data = iris)
get_info_data <- function(data) {
  
  dimensions = dim(data)
  column_names = colnames(data)
  
  result <- list(dimensions = dimensions, column_names = column_names)
  
  if(is.null(result$dimensions) & is.null(result$column_names)){
    stop("This is not a list")
  } else {
    return(result)
  }
    
}
